.eslintignore
.eslintrc
.gitignore
.prettierrc
.travis.yml
lib/classes/alias.js
lib/classes/asset.js
lib/classes/import-map.js
lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.put.js
lib/handlers/asset.post.js
lib/handlers/import-map.delete.js
lib/handlers/import-map.get.js
lib/handlers/import-map.put.js
lib/sinks/fs.js
lib/sinks/gcs.js
lib/utils/utils.js
package.json
services/fastify.js
test/fixtures/file.js
test/index.test.js

I noticed that what was written in the docs for alias creation was not the actual behaviour. I've lined up the behaviour with the docs
In the process i've lined up the fs sink write method so that it has the same signature as the gcs write method signature. Problem is that to do so I've had to add a blocking operation. I've added a TODO in there to fix. Not sure what the best approach is. Easiest would be if both write methods just returned promises that resolved to write streams.
Later commits add linting and fix lint issues.
I will fix up tests to match latest spec next

Clean up alias

---

lib/handlers/asset.post.js
test/classes/alias.js
test/classes/asset.js
test/classes/http-incoming.js
test/classes/http-outgoing.js
test/classes/import-map-entry.js
test/classes/import-map.js
test/classes/upload-log.js

@trygve-lie can I get your opinion on this? I've added a little extra guarding around the 'done' event emission which I discovered during testing can have already fired before the _final method is called there by hanging the stream forever. This was the first solution that hit me but maybe there is a nicer way to ensure that no matter when the _final method is called, it won't miss the done event?
I've isolated the change to [this commit](https://github.com/asset-pipe/core/pull/4/commits/67e480e692795b1245cf36a35ebc6023c42b9bc6) if you want to avoid looking at the lint fix noise

Refactor assets

---

lib/sinks/fs.js
lib/sinks/gcs.js

This appends a `.exist()`method to both sinks. We need such methods to check if something exist in the a storage in different routes.

Add .exist() method

---

fixtures/sink-test.js
lib/main.js
lib/sinks/fs.js
package.json
services/fastify.js
test/integration/fastify.js

This creates one public entry point for the core module by pulling all handler, sink and public global values into one main file which is exposed with selected properties.
Currently these are exported methods and properties. We might want this to export an constructor instead at one point.

Add public entry point for module

---

doc/rest-api.md
examples/map.put.js
lib/handlers/map.put.js
lib/utils/utils.js
package.json
services/fastify.js
test/integration/fastify.js

This simplifies and hardens the import map put handler.
One notable change is that when a successful upload is done it will respond with a http 303 redirect instead of a 2xx status. The redirect points to the GET URI of the import map. The advantage of this is that the client can follow the redirect and get the uploaded import map from the GET route when its done uploading. When a http cache are in front of the GET route this will populate the http cache with the image map upon upload.

Simplify import map put handler

---

fixtures/sink-test.js
services/fastify.js
test/integration/fastify.js
test/integration/pkg-put-write-Integrity.js

This ads a test for the package PUT feature where the sink is slow to write. 
Each chunk of a stream written to the sink is slowed down with a random time between 10ms and 100ms making the write process slow and inconsistent. In theory this should make it possible to catch any race conditions or early termination of streams piping into a sink.

Test slow pkg PUT writes

---

examples/map.alias.post.js
lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/map.get.js
lib/handlers/map.put.js
lib/handlers/pkg.get.js
lib/handlers/pkg.put.js
lib/main.js
services/fastify.js

This turns all handlers into classes where the constructor takes a sink, a config object and a logger.
The `main` export of this module does now export all the classes so its possible to pull in one file and get holds of all classes like so:
```js
const { http } = require('core');
const app = require('express')();
const aliasPost = new http.AliasPost(sink, {}, logger);
const aliasDel = new http.AliasDel(sink, {}, logger);
const aliasGet = new http.AliasGet(sink, {}, logger);
const aliasPut = new http.AliasPut(sink, {}, logger);
const pkgGet = new http.PkgGet(sink, {}, logger);
const pkgPut = new http.PkgPut(sink, {}, logger);
const mapGet = new http.MapGet(sink, {}, logger);
const mapPut = new http.MapPut(sink, {}, logger);
app.get('/.....', (req, res) => {
const outgoing = …
```

Turn all handlers into classes

---

examples/pkg.put.js
lib/handlers/pkg.put.js
lib/sinks/fs.js
test/integration/fastify.js

This appends a check to see if a package already exists when uploading. If not, its created with a 201 http status code. If it exist its not created with a 409 http status code.

Check if package exists before upload

---

doc/rest-api.md
examples/map.alias.delete.js
examples/map.alias.post.js
examples/map.alias.put.js
examples/pkg.alias.delete.js
examples/pkg.alias.post.js
examples/pkg.alias.put.js
examples/pkg.put.js
fixtures/sink-test.js
lib/handlers/alias.delete.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
test/integration/fastify.js

This appends an exist check to all the methods which alters aliases. The following will now happen:
- If a given alias does **not** exist, a `PUT` will create the alias and result in a 303 HTTP status.
- If a given alias does exist, a `PUT` will error by responding with a 409 HTTP status.
- If a given alias does **not** exist, a `POST` will error by responding with a 404 HTTP status.
- If a given alias does exist, a `POST` will update the alias and result in a 303 HTTP status.
- If a given alias does **not** exist, a `DELETE` will error by responding with a 404 HTTP status.
- If a given alias does exist, a `DELETE` will remove the alias and result in a 204 HTTP status.
Do note: some HTTP statuses have changed from what it was previously. This might have to be compensated by in the client.

Check if aliases exist on all methods which alter an alias

---

doc/rest-api.md
examples/pkg.put.js
lib/classes/upload-log.js
lib/handlers/pkg.log.js
lib/handlers/pkg.put.js
lib/main.js
lib/sinks/fs.js
lib/utils/pathnames.js
lib/utils/paths.js
services/fastify.js
test/integration/fastify.js

This exposes the upload log of a package on the root of a package `/:org/pkg/:name/:version`. It will return the following object:
```js
{
version: '8.4.1',
name: 'fuzz',
org: 'biz',
files: [
{
mimeType: 'application/javascript',
pathname: '/biz/pkg/fuzz/8.4.1/main/index.js',
type: 'file',
size: 75208
},
... snip ...
],
meta: []
}
```
It also changes the HTTP status on `PUT` for the package from a 201 to a 303 which redirects to the upload log instead of returning it as a part of the body. When creating or updating a alias on a package these will now also redirect to this destination.
This raises one question though; 
Currently `/:org/pkg/:name/:version` will return this log file but I am not sure if that is the best location to expose this log file on. If we look at similar systems a …

Expose the package upload log

---

lib/classes/alias.js
lib/classes/asset.js
lib/classes/http-outgoing.js
lib/classes/meta.js
lib/classes/package.js
lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/map.get.js
lib/handlers/map.put.js
lib/handlers/pkg.get.js
lib/handlers/pkg.log.js
lib/handlers/pkg.put.js
lib/sinks/fs.js
lib/sinks/mem.js
lib/utils/defaults.js

This appends a default config which can be overrided on the constructor of different classes. This makes it possible to pass in a full config when used in a standalone http server or just parts of a config when each handler is run as a cloud function.

Added config

---

lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/map.get.js
lib/handlers/map.put.js
lib/handlers/pkg.get.js
lib/handlers/pkg.log.js
lib/handlers/pkg.put.js
package.json
services/fastify.js

This adds logging to all handlers. All `GET` routes has most logging set to `debug` as the lowest level to minimize noise in production while all `PUT`, `POST` and `DELETE` routes has lowest level set to `info` so we can track modification on the server in production.

Add logging

---

doc/rest-api.md
examples/pkg.put.js
lib/handlers/pkg.put.js
test/integration/fastify.js
test/integration/pkg-put-write-integrity.js

This changes the field name of the field for the package tar file from `filedata` to `package`. Makes it a bit more intuitive. The client needs to align with this.

Change form field for tar file to be named package

---

services/fastify.js

Avoids getting these warning messages on start:
```sh
(node:13679) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
```

Avoid hitting max listeners exceeded warning

---

lib/sinks/fs.js
lib/sinks/mem-entry.js
lib/sinks/mem.js
lib/sinks/test.js
test/sinks/fs.js
test/sinks/mem.js
test/sinks/test.js

When serving files we need to detect the mime type of each file so it can be set on the request headers. 
When running on a memory of `fs` sink, this needs to be parsed out of the request, but if running on a cloud storage bucket we can get this information from the buckets. We should do mime type parsing part of the sinks instead of the incoming http request. This PR appends mime type handling as part of the sink.

Make mime type detection part of the sinks

---

services/fastify.js

Remove small hack used to load GCS config. This is now handled by the GCS sink as it should.

Do not read GCS info from core

---

package.json
services/fastify.js

This removed the metric collector which was previously added and exposes a `.metrics` property with a metric stream instead. Collecting the metrics belong in the server code consuming this module.
This does also remove `pino` as logger and uses only `abslog` for the same above reason.

Remove metric collector and specific logger

---

lib/sinks/fs.js
lib/sinks/mem.js
lib/sinks/test.js
package.json

This makes use of the new @eik/sink module instead of the sink which was in @eik/common.

Use @eik/sink module

---

examples/npm.alias.delete.js
examples/npm.alias.get.js
examples/npm.alias.post.js
examples/npm.alias.put.js
examples/npm.get.js
examples/npm.put.js
lib/classes/package.js
lib/classes/versions.js
lib/handlers/pkg.get.js
lib/handlers/pkg.log.js
lib/handlers/pkg.put.js
lib/main.js
lib/utils/globals.js
lib/utils/path-builders-fs.js
lib/utils/path-builders-uri.js
package.json

This ads support for keeping npm as a package type. By introducing this, packages from npm is kept separate from "private" packages. This will avoid possible naming collisions.

Support npm as package type

---

lib/classes/http-outgoing.js
lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/auth.post.js
lib/handlers/map.get.js
lib/handlers/map.put.js
lib/handlers/pkg.get.js
lib/handlers/pkg.log.js
lib/handlers/pkg.put.js
lib/handlers/versions.get.js

This appends sensible http cache control headers to all routes.
* All `PUT`, `POST` and `DELETE` routes is set to not be cached or stored. 
* The packages and map `GET` routes is set to be forever cached. 
* The packages log and version `GET` routes is set to be not cached but re-validated.
* The packages and map alias `GET` redirects is set to be cached for 20 minutes.
This also changes the http status code on packages and map alias `GET` redirects from a `303` to a `307` which is more correct.

Add sensible cache control defaults

---

lib/main.js
lib/utils/healthcheck.js
package.json
test/utils/healthchecks.js

This ads a sink health check. It does all the operations the service need to do to operate on files in a storage to work properly. If all checks pass it will report success. If any steps fails it will report which step failed.

Add health check for checking the sink

---

lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/auth.post.js
lib/handlers/map.get.js
lib/handlers/map.put.js
lib/handlers/pkg.get.js
lib/handlers/pkg.log.js
lib/handlers/pkg.put.js
lib/handlers/versions.get.js

This ads predefined buckets to histograms to reduce the amount of permutations in the metrics.

fix: Add buckets to histograms

---

lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/auth.post.js
lib/handlers/map.get.js
lib/handlers/map.put.js
lib/handlers/pkg.get.js
lib/handlers/pkg.log.js
lib/handlers/pkg.put.js
lib/handlers/versions.get.js

The request handlers can be used between http routes. Ex, the same handlers are used to handle both eik packages and npm packages, the only thing separating them is a `type` which can be `pkg` or `npm` in the URLs and on the file system.
This adds a `type` label on the metrics to all handlers which reflects the `type` value used to separate this in the URLs and on the file system making it possible to differentiate on this in the metrics.

fix: Add type as label to histograms

---

lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/map.get.js
lib/handlers/map.put.js
lib/handlers/pkg.get.js
lib/handlers/pkg.log.js
lib/handlers/pkg.put.js
lib/handlers/versions.get.js
lib/utils/utils.js
test/handlers/alias.delete.js
test/handlers/alias.get.js
test/handlers/alias.post.js
test/handlers/alias.put.js
test/handlers/map.get.js
test/handlers/map.put.js
test/handlers/pkg.get.js
test/handlers/pkg.log.js
test/handlers/pkg.put.js
test/handlers/versions.get.js
test/utils/utils.js

This decodes URL encoded URL parameters. 
For the record; When using the client directly against the server URL params with characters such a `@` is handled without any encoding / decoding. This was first discovered when the server run behind a HTTP cache which seems to encode such characters.

feat: Decode URL encoded URL parameters

---

lib/main.js

Currently the `@eik/service` is using the internal test sink but its referencing it by dotting into the `node_folder`. This is brittle and should not be done and is also causing the [following lint error](https://github.com/eik-lib/service/pull/300) in the `@eik/service` module:
```sh
Error:   10:18  error  Relative import from another package is not allowed. Use `@eik/core/lib/sinks/test.js` instead of `../node_modules/@eik/core/lib/sinks/test.js`  import/no-relative-packages
```
This exposes the test sink in the same way as we are exposing the file system and memory sink.

fix: Expose the internal test sink

---

lib/handlers/map.get.js
lib/handlers/map.put.js
lib/handlers/pkg.get.js
lib/handlers/versions.get.js

One handler had a duplicate logger defined. Also cleaned out some whitespace.

fix: Removed duplicate logger

---

lib/multipart/parser.js

We've seen some errors for archives with a large number of files, but without logging we're guessing a bit more than we'd like.
Fixes #418

fix: add some logging in case archive parsing fails

---

lib/utils/healthcheck.js

Open for discussing this. Another option is of course to increase the loglevel to WARN if you think this is too verbose.

fix: make healthcheck logging less verbose by default

---

.github/workflows/test.yml
lib/classes/asset.js
lib/sinks/test.js
lib/utils/path-builders-uri.js
lib/utils/url.js
package.json

Depends on:
- https://github.com/eik-lib/common/pull/303
- https://github.com/eik-lib/sink-memory/pull/5

fix: windows support

---

lib/handlers/map.get.js
lib/handlers/pkg.get.js
lib/handlers/pkg.log.js
lib/handlers/versions.get.js
lib/sinks/test.js
test/handlers/pkg.get.js

We measure the action as done when the stream is returned, not when the stream itself is finished. This could be misleading.
[See the difference between `END` and `FINISH`](https://github.com/eik-lib/core/actions/runs/17125749161/job/48576899364?pr=503#step:7:429).
```
END 2181.057062
FINISH 12189.26404
ok 1 - should respond with expected status code
ok 2 - should be possible to retrieve a payload when handlers values is URL encoded
1..2
ok 1 - pkg.get() - URL parameters is URL encoded # time=10025.446ms
1..1
```

fix: end timer on stream end or error 
