lib/utils/validators.js
package.json
test/utils/validators.js

Adding some validators for input validation.

Add validators

---

doc/rest-api.md

Makes the curl examples for each method work with the implemented API and the provided [fixture package](https://github.com/asset-pipe/core/tree/master/fixtures).

Make curl examples usable

---

.github/workflows/nodejs.yml
.github/workflows/pr_target_master.yml
examples/pkg.put.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/sinks/mem.js
package.json
services/fastify.js
test/integration/fastify.js
test/integration/utils/extract-body.js
test/integration/utils/fixture.js

Adding a first pass of integration tests for the various endpoints

Add integration tests

---

test/integration/fastify.js

This PR adds basic import map tests

round out basic integration tests

---

fixtures/sink-test.js
lib/handlers/pkg.put.js
lib/sinks/fs.js
lib/sinks/gcs.js
lib/utils/utils.js

Quick pass over the files to fix eslint

format and fix lint issues in files

---

lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js

Redirects are 303's, not 302's.

Redirects should be 303

---

lib/handlers/alias.delete.js
services/fastify.js

Harden the alias delete route.

Harden alias delete handler 

---

lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/utils/validators.js
services/fastify.js
test/utils/validators.js

Add validation of the `type` property used in aliases.

Validate the type property

---

examples/map.alias.get.js
examples/map.alias.post.js
examples/map.alias.put.js
examples/map.get.js
examples/pkg.alias.post.js
examples/pkg.alias.put.js
examples/pkg.get.js
lib/sinks/gcs.js

This aligns the GCS sink with the FS sink.

Align GCS sink with FS sink

---

examples/map.put.js
examples/pkg.put.js
lib/handlers/map.put.js

This appends a check to see if a map already exists when uploading. If not, its created with a 303 HTTP status code. If it exist its not created and responds with a 409 HTTP status code.

Check if map exists before upload

---

doc/rest-api.md
examples/map.alias.delete.js
examples/map.alias.post.js
examples/map.alias.put.js
examples/pkg.alias.delete.js
examples/pkg.alias.post.js
examples/pkg.alias.put.js
examples/pkg.put.js
fixtures/sink-test.js
lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/map.get.js
lib/handlers/pkg.get.js
test/integration/fastify.js

Use http error method names instead of setting code and message manually.

Use http error method names

---

lib/classes/asset.js
lib/classes/package.js
lib/handlers/pkg.put.js
package.json

This add a integrity hash of all the files in a uploaded package. The hash is a SHA512 base64 encoded.

Add integrity hash

---

doc/file-structure.md
doc/rest-api.md
lib/classes/http-outgoing.js
lib/classes/meta.js
lib/classes/versions.js
lib/handlers/map.put.js
lib/handlers/pkg.put.js
lib/handlers/versions.get.js
lib/main.js
lib/utils/path-builders-fs.js
package.json
services/fastify.js
test/classes/alias.js
test/classes/http-incoming.js
test/classes/http-outgoing.js
test/classes/meta.js
test/classes/read-file.js
test/classes/versions.js

This adds an overview of the latest versions for packages and import maps. The overview points each major to the latest version of that major.
The overview for a package is available at ex: `http://localhost:4001/biz/pkg/bizz`.
The overview for a import map is available at ex: `http://localhost:4001/biz/map/buzz`.

Add version overview

---

lib/handlers/pkg.put.js

Fixes hashing of uploaded files in a compressed tar file.

Fix hashing of uploaded files

---

lib/handlers/alias.delete.js
lib/handlers/alias.get.js
lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/map.get.js
lib/handlers/map.put.js
lib/handlers/pkg.get.js
lib/handlers/pkg.log.js
lib/handlers/pkg.put.js
lib/handlers/versions.get.js
package.json
services/fastify.js

adds basic route handler timing metrics and a prometheus scraping page

Add metrics

---

lib/handlers/alias.post.js
lib/handlers/alias.put.js
lib/handlers/map.put.js
lib/handlers/pkg.put.js

This cleans up all the `PUT` and `POST` methods. They started to get a bit of promise x-mass trees so this does more or less just flatten the code.

Flatten promise structures

---

services/fastify.js

2 things happening here:
1. I've added an address option to the constructor because it turns that fastify doesn't behave quite the same as express in that you need to expressly set the bind address (or '0.0.0.0') or it will only bind to localhost and your app won't seem to work when you push to dev/prod.
2. Another adjustment to logging. I think realistically, with Fastify, just use Pino. Abslog does support pino as a logger but the noop logger does not provide a child method like pino does so trying to set `fastify({ logger: abslog(null) });` doesn't cut it. This is fine, as in that case, we can just set `fastify({ logger: false });` which is what I've done here.

add address arg and adjust passing logger

---

lib/handlers/map.put.js
lib/multipart/parser.js
package.json
test/multipart/parser.js

Busboy version 1.3.0 has a couple of [breaking API changes](https://github.com/mscdex/busboy/issues/266). This PR cater for these changes.

fix: Upgrade to major version 1.3.0 of Busboy

---

lib/classes/versions.js
lib/handlers/pkg.put.js
lib/utils/path-builders-fs.js
lib/utils/utils.js
test/classes/versions.js
test/handlers/pkg.get.js
test/handlers/pkg.put.js

Pardon the naive approach to fixing previous versions. This is an attempt to get the ball rolling on https://github.com/eik-lib/core/issues/73.

Solves issue #73

---

lib/sinks/test.js

Solves the performance regression introduced in #435

fix: performance regression in test sink

---

lib/main.js
lib/utils/globals.js
package.json

Step 2 of adding a new /img namespace to Eik
Needs: https://github.com/eik-lib/common/pull/326

feat: add support for Eik image type
